# Generated by Django 4.1.7 on 2023-03-08 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemark',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='games.game'),
        ),
    ]
