# Generated by Django 4.1.7 on 2023-03-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_profile_achievements'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gamemark',
            constraint=models.UniqueConstraint(fields=('game', 'user'), name='unique game for user'),
        ),
    ]
