# Generated by Django 4.1.7 on 2023-03-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_gamemark_unique game for user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='gamemark',
            name='comment',
            field=models.TextField(verbose_name='Комментарий'),
        ),
    ]
