# Generated by Django 4.1.7 on 2023-03-30 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_game_options_alter_gamemark_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemark',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamemarks', to='games.game', verbose_name='Игра'),
        ),
    ]
